crontab will be added soon

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -65,16 +65,16 @@ function create() #from to pattern backup_name
     exit 1;
   fi
   
-  mkdir ${output_dir}/${name};
+  mkdir ${output_dir}${name};
   tar_name=$(date +"%Y%m%d_%H%M%S").tar;
-  if ! tar -cf ${output_dir}/${name}/${tar_name} ${input_dir}${pattern} 2>> ./errors.log; then
+  if ! tar -cf ${output_dir}${name}/${tar_name} ${input_dir}${pattern} 2>> ./errors.log; then
     echo "Error in creating tar archive.";
-    rm ${output_dir}/${name}/${tar_name};
+    rm ${output_dir}${name}/${tar_name};
     exit 2;
   fi
-  sha512sum ${output_dir}/${name}/${tar_name} > ${output_dir}/${name}/${tar_name}.sum;
+  sha512sum ${output_dir}${name}/${tar_name} > ${output_dir}${name}/${tar_name}.sum;
   
-  echo -e "${name}\t0\t0\t${input_dir}\t${output_dir}/${name}\t$3" >> ~/.config/anytask_backup/backup.conf;
+  echo -e "${name}\t0\t0\t${input_dir}\t${output_dir}${name}/\t$3" >> ~/.config/anytask_backup/backup.conf;
   exit 0;
 }
 
@@ -82,6 +82,7 @@ function plan() #mode name
 {
   mode=$1;
   name=$2;
+  script_name="$(realpath $3)";
   if [ -z "${mode}" ]; then
     echo "Type error. Missing arg 'mode'.";
     exit 1;
@@ -89,6 +90,45 @@ function plan() #mode name
     echo "Type error. Missing arg 'name'.";
     exit 1;
   fi
+  
+  record="$(awk -v backup_name=${name} 'BEGIN {res=0} {if ($1 == backup_name) res=$0} END {print res}' ~/.config/anytask_backup/backup.conf)";
+  if test "${record}" -eq 0 2> /dev/null; then
+    echo "Type error. This backup not found. Create it using 'backup create' command.";
+    exit 1;
+  fi
+  
+  case "${mode}" in
+  
+  "-d" | "--daily" )
+  crontan -l > crontab.tmp;
+  #awk -v name=${name} '{if ($1==name) $6="-d"} {print $0}}' ;
+  #echo "0 17 * * ${script_name} ${name}" >> crontab.tmp;
+  #awk -v name=${name} '{if ($1==name) $2="-d"} {print $0}}' ~/.config/anytask_backup/backup.conf;
+  #crontab 
+  
+  
+  echo "${record}";
+  exit 0;
+  ;;
+
+  "-w" | "--weekly" )
+  echo "weekly script";
+  exit 0;
+  ;;
+  
+  "-m" | "--monthly" )
+  echo "monthly script";
+  exit 0;
+  ;;
+  
+  "-0" | "--off" )
+  echo "of script";
+  exit 0;
+  ;;
+  esac
+  
+  echo "Type error. plan mode is incorrect."
+  exit 1;
   
   echo "CODE";
 }
@@ -110,16 +150,14 @@ function getHelp()
 
 if [ ! -d ~/.config/anytask_backup ]; then
   mkdir ~/.config/anytask_backup;
-  touch ~/.config/anytask_backup/backup.conf;
 fi
 touch ~/.config/anytask_backup/backup.conf;
 
-echo ~/.config;
 if [[ "$1" == "create" ]]; then
   #what where pattern name
   create $2 $3 $4 $5;
 elif [[ "$1" == "plan" ]]; then
-  plan $2 $3;
+  plan $2 $3 $0;
 elif [[ "$1" == "delete" ]]; then
   #backup_name
   delete $2
@@ -132,6 +170,6 @@ elif [[ "$1" == "--help" ]]; then
   getHelp;
 else
   echo "Type error. try backup --help for info";
-  exit -1;
+  exit 1;
 fi
 exit 0;
